const crypto = require('crypto');
const { promisify } = require('util');
const scrypt = promisify(crypto.scrypt);
let kdfActive=0;const kdfQueue=[];const KDF_MAX=2,KDF_QUEUE_MAX=12;
async function withKdf(work){if(kdfActive>=KDF_MAX){if(kdfQueue.length>=KDF_QUEUE_MAX){const e=new Error('认证繁忙，请稍后重试');e.code='KDF_BUSY';throw e;}await new Promise(resolve=>kdfQueue.push(resolve));}kdfActive++;try{return await work();}finally{kdfActive--;kdfQueue.shift()?.();}}
const now = () => new Date().toISOString();
const id = () => crypto.randomUUID();
const hashToken = value => crypto.createHash('sha256').update(value).digest('hex');
const validateEmail=value=>{const email=String(value||'').trim().toLowerCase();if(email.length>254||!/^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(email))throw new Error('邮箱格式无效');return email;};
const validatePassword=value=>{if(typeof value!=='string'||value.length<12||value.length>1024)throw new Error('密码长度必须为 12-1024 个字符');return value;};
async function hashPassword(password) { validatePassword(password); return withKdf(async()=>{const salt=crypto.randomBytes(16);const value=await scrypt(password,salt,64,{N:16384,r:8,p:1,maxmem:64*1024*1024});return `scrypt$N=16384,r=8,p=1$${salt.toString('base64')}$${value.toString('base64')}`;}); }
async function verifyPassword(password, encoded) { try { const [,params,salt,hash]=encoded.split('$');const config=Object.fromEntries(params.split(',').map(v=>v.split('=')));const actual=await withKdf(()=>scrypt(password,Buffer.from(salt,'base64'),64,{N:Number(config.N),r:Number(config.r),p:Number(config.p),maxmem:64*1024*1024}));const expected=Buffer.from(hash,'base64');return actual.length===expected.length&&crypto.timingSafeEqual(actual,expected); } catch (error) { if(error.code==='KDF_BUSY')throw error;return false; } }
class AuthService {
  constructor(storage){this.db=storage.db;}
  setting(key, fallback=null){return this.db.prepare('SELECT value FROM instance_settings WHERE key=?').get(key)?.value ?? fallback;}
  setSetting(key,value){this.db.prepare('INSERT OR REPLACE INTO instance_settings(key,value) VALUES (?,?)').run(key,String(value));}
  async bootstrapOwner(email,password){const password_hash=await hashPassword(password);const time=now();const user={id:id(),email:email.toLowerCase(),password_hash,role:'owner',enabled:1,created_at:time,updated_at:time};this.db.exec('BEGIN IMMEDIATE');try{if(this.setting('owner_initialized')||this.db.prepare("SELECT id FROM users WHERE role='owner'").get())throw new Error('实例已初始化');this.db.prepare('INSERT INTO users VALUES (@id,@email,@password_hash,@role,@enabled,@created_at,@updated_at)').run(user);this.setSetting('owner_initialized','1');this.audit(user.id,'bootstrap','user',user.id);this.db.exec('COMMIT');return this.publicUser(user);}catch(e){this.db.exec('ROLLBACK');throw e;}}
  publicUser(user){const {password_hash,...safe}=user;return safe;}
  createSession(user, days=14){const token=crypto.randomBytes(32).toString('base64url');const time=now();this.db.prepare('INSERT INTO sessions VALUES (?,?,?,?,?,?)').run(id(),user.id,hashToken(token),new Date(Date.now()+days*864e5).toISOString(),time,time);return token;}
  session(token){const row=this.db.prepare('SELECT s.*,u.email,u.role,u.enabled FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token_hash=? AND s.expires_at>?').get(hashToken(token),now());if(!row||!row.enabled)return null;this.db.prepare('UPDATE sessions SET last_seen_at=? WHERE id=?').run(now(),row.id);return {id:row.user_id,email:row.email,role:row.role};}
  async login(email,password){email=validateEmail(email);validatePassword(password);const user=this.db.prepare('SELECT * FROM users WHERE email=?').get(email);const dummy='scrypt$N=16384,r=8,p=1$AAAAAAAAAAAAAAAAAAAAAA==$AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==';let ok=false;try{ok=await verifyPassword(password,user?.password_hash||dummy);}catch(e){if(e.code==='KDF_BUSY')throw e;}if(!user||!user.enabled||!ok)throw new Error('邮箱或密码错误');return {user:this.publicUser(user),token:this.createSession(user)};}
  logout(token){this.db.prepare('DELETE FROM sessions WHERE token_hash=?').run(hashToken(token));}
  logoutAll(userId){this.db.prepare('DELETE FROM sessions WHERE user_id=?').run(userId);}
  createInvitation(actor,email,role='user',ttlHours=72){if(role==='owner'||!['user','admin'].includes(role))throw new Error('无效邀请角色');const token=crypto.randomBytes(32).toString('base64url'),time=now();this.db.prepare('INSERT INTO invitations VALUES (?,?,?,?,?,?,?,?,?)').run(id(),email?.toLowerCase()||null,role,hashToken(token),new Date(Date.now()+ttlHours*36e5).toISOString(),null,null,actor.id,time);this.audit(actor.id,'invite.create','invitation',null,{email,role});return token;}
  revokeInvitation(actor,idValue){const invite=this.db.prepare('SELECT * FROM invitations WHERE id=?').get(idValue);if(!invite)throw new Error('邀请不存在');this.db.prepare('UPDATE invitations SET revoked_at=? WHERE id=?').run(now(),idValue);this.audit(actor.id,'invite.revoke','invitation',idValue);}
  async acceptInvitation(token,email,password){if(typeof token!=='string'||token.length<32||token.length>256)throw new Error('邀请格式无效');email=validateEmail(email);const password_hash=await hashPassword(password),time=now();this.db.exec('BEGIN IMMEDIATE');try{const invite=this.db.prepare('SELECT * FROM invitations WHERE token_hash=? AND revoked_at IS NULL AND accepted_at IS NULL AND expires_at>?').get(hashToken(token),time);if(!invite)throw new Error('邀请无效、已过期或已使用');if(invite.email&&invite.email!==email)throw new Error('邀请邮箱不匹配');const claimed=this.db.prepare('UPDATE invitations SET accepted_at=? WHERE id=? AND revoked_at IS NULL AND accepted_at IS NULL AND expires_at>?').run(time,invite.id,time);if(claimed.changes!==1)throw new Error('邀请已被领取');const user={id:id(),email,password_hash,role:invite.role,enabled:1,created_at:time,updated_at:time};this.db.prepare('INSERT INTO users VALUES (@id,@email,@password_hash,@role,@enabled,@created_at,@updated_at)').run(user);this.audit(user.id,'invite.accept','invitation',invite.id);this.db.exec('COMMIT');return this.publicUser(user);}catch(e){this.db.exec('ROLLBACK');throw e;}}
  async register(email,password){if(this.setting('allow_public_registration','false')!=='true')throw new Error('未开放公开注册');const time=now(),user={id:id(),email:String(email).toLowerCase(),password_hash:await hashPassword(password),role:'user',enabled:1,created_at:time,updated_at:time};this.db.prepare('INSERT INTO users VALUES (@id,@email,@password_hash,@role,@enabled,@created_at,@updated_at)').run(user);return this.publicUser(user);}
  listUsers(){return this.db.prepare('SELECT id,email,role,enabled,created_at,updated_at FROM users ORDER BY created_at').all();}
  listInvitations(){return this.db.prepare('SELECT id,email,role,expires_at,accepted_at,revoked_at,created_at FROM invitations ORDER BY created_at DESC').all();}
  listAudit(limit=100){return this.db.prepare("SELECT a.id,a.action,a.target_type,a.target_id,a.created_at,u.email AS actor_email FROM audit_events a LEFT JOIN users u ON u.id=a.actor_user_id ORDER BY a.created_at DESC LIMIT ?").all(Math.min(200,Math.max(1,Number(limit)||100)));}
  setUser(actor,targetId,changes){if(!changes||Object.keys(changes).some(key=>!['role','enabled'].includes(key)))throw new Error('包含不允许的用户字段');const normalized={};if(Object.hasOwn(changes,'enabled')){if(typeof changes.enabled!=='boolean')throw new Error('enabled 必须为布尔值');normalized.enabled=changes.enabled;}if(Object.hasOwn(changes,'role')){if(!['user','admin'].includes(changes.role))throw new Error('角色只能为 user 或 admin');normalized.role=changes.role;}if(!Object.keys(normalized).length)throw new Error('没有可更新的字段');const target=this.db.prepare('SELECT * FROM users WHERE id=?').get(targetId);if(!target)throw new Error('用户不存在');if(target.id===actor.id&&normalized.enabled===false)throw new Error('不能禁用自己');if(target.role==='owner'&&actor.role!=='owner')throw new Error('不能操作 Owner');if(actor.role==='admin'&&target.role!=='user')throw new Error('管理员只能管理普通用户');if(normalized.role&&actor.role!=='owner')throw new Error('只有 Owner 可修改角色');if(Object.hasOwn(normalized,'enabled'))this.db.prepare('UPDATE users SET enabled=?,updated_at=? WHERE id=?').run(normalized.enabled?1:0,now(),targetId);if(normalized.role)this.db.prepare('UPDATE users SET role=?,updated_at=? WHERE id=?').run(normalized.role,now(),targetId);this.audit(actor.id,'user.update','user',targetId,normalized);}
  quota(userId){return this.db.prepare('SELECT user_id,mail_account_limit,notification_limit FROM quotas WHERE user_id=?').get(userId)||{user_id:userId,mail_account_limit:null,notification_limit:null};}
  setQuota(actor,userId,values){if(!values||Object.keys(values).some(key=>!['maxAccounts','maxNotificationChannels'].includes(key)))throw new Error('包含不允许的配额字段');const normalize=value=>{if(value===null||value===undefined||value==='')return null;if(!Number.isInteger(value)||value<0||value>100000)throw new Error('配额必须是 0–100000 的整数或留空');return value;};const normalized={maxAccounts:normalize(values.maxAccounts),maxNotificationChannels:normalize(values.maxNotificationChannels)};this.db.prepare('INSERT OR REPLACE INTO quotas(user_id,mail_account_limit,notification_limit) VALUES (?,?,?)').run(userId,normalized.maxAccounts,normalized.maxNotificationChannels);this.audit(actor.id,'quota.update','user',userId,normalized);}
  async changePassword(userId,currentPassword,nextPassword){const user=this.db.prepare('SELECT * FROM users WHERE id=?').get(userId);if(!user||!(await verifyPassword(currentPassword,user.password_hash)))throw new Error('当前密码错误');this.db.prepare('UPDATE users SET password_hash=?,updated_at=? WHERE id=?').run(await hashPassword(nextPassword),now(),userId);this.logoutAll(userId);}
  audit(actor,action,type=null,target=null,metadata={}){this.db.prepare('INSERT INTO audit_events VALUES (?,?,?,?,?,?,?)').run(id(),typeof actor==='object'?actor.id:actor,action,type,target,JSON.stringify(metadata),now());}
}
module.exports={AuthService,hashPassword,verifyPassword,hashToken};
